apiVersion: v2
name: kafdrop
version: 0.2.0
description: A Helm chart for Kafdrop on Kubernetes
type: application
keywords:
  - kafka
  - kafdrop
home: https://github.com/ricardo-aires/helm-charts
sources:
  - https://github.com/ricardo-aires/helm-charts
  - https://github.com/obsidiandynamics/kafdrop
maintainers:
  - name: Ricardo Henriques
    email: ricardoaireshenriques@gmail.com
    url: https://github.com/ricardo-aires
appVersion: 3.30.0
